### ISSUE TITLE
Feature request: Enable Browserless Access for pyoverleaf API

### ISSUE THREAD

**Issue by wongsingfo** [jkulhanek/pyoverleaf#1]
Thank you for creating the remarkable API that facilitates access to Overleaf projects!

Currently, the pyoverleaf library relies on [browsercookie](https://github.com/richardpenman/browsercookie) to retrieve the necessary cookies for Overleaf access. While this approach works well for many, it poses a challenge for users who lack a graphical user interface on their servers. Given the increasing number of individuals leveraging pyoverleaf in environments devoid of a desktop interface, I believe this concern might be relatively common.

From my understanding, the essential cookies required for this purpose are `GCLB` and `overleaf_session2`. In light of this, I would like to propose a potential enhancement. It would be immensely helpful if pyoverleaf could be extended to accept cookies as arguments during function calls or alternatively, if cookies could be managed via the pyoverleaf APIs themselves.

For reference, the relevant code snippet can be found here: 

https://github.com/jkulhanek/pyoverleaf/blob/9bb9a0a38aaa9b73b04c427e3969d821b66bcd0f/pyoverleaf/_webapi.py#L360-L365

**Comment by jkulhanek** [comment]
Good idea. First I wanted to allow login with username and password, but there is a captcha verification. But passing cookies manually is a viable option.

**Comment by jkulhanek** [comment]
It is now enabled by `api.login_from_cookies(...)`

**Comment by wongsingfo** [comment]
Hi, it seems that the cookiejar.cookie is not properly initialized.

Here is the stacktrace and the relevant code.

```
File /usr/local/lib/python3.11/site-packages/pyoverleaf/_webapi.py:343, in Api.login_from_cookies(self, cookies)
    341     cookies_jar = cookielib.CookieJar()
    342     for name, value in cookies.items():
--> 343         cookies_jar.set_cookie(cookielib.Cookie(
    344             name=name,
    345             value=value,
    346             domain=".overleaf.com"))
    347     cookies = cookies_jar
    349 assert isinstance(cookies, cookielib.CookieJar)

TypeError: Cookie.__init__() missing 13 required positional arguments: 'version', 'port', 'port_specified', 'domain_specified', 'domain_initial_dot', 'path', 'path_specified', 'secure', 'expires', 'discard', 'comment', 'comment_url', and 'rest'
```

https://github.com/python/cpython/blob/429749969621b149c1a7c3c004bd44f52bec8f44/Lib/http/cookiejar.py#L743-L772

https://github.com/jkulhanek/pyoverleaf/blob/0685f3c9ccd06502773c965f65c92d9a6bbc7765/pyoverleaf/_webapi.py#L5-L8
