### ISSUE TITLE
Working on the Typescript version API

### ISSUE THREAD

**Issue by iamhyc** [jkulhanek/pyoverleaf#2]
Hi, just searched this cool project on stackoverflow!

I am working on a similar project:  a extension to open overleaf in vscode editor, [Overleaf-Workshop](https://github.com/iamhyc/overleaf-workshop).

I am also in the "reverse engineering" stage and most of my current results are not verified. Anyway, I am just here to say hi :)

**Comment by jkulhanek** [comment]
Hi, vscode integration sounds really great! Looking forward to your extension! Let me know if you need any help.
